# Generated by Django 4.2.16 on 2024-09-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardroom', '0002_alter_wardrobeitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='season',
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
