# Generated by Django 4.2.16 on 2024-09-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardroom', '0004_alter_outfit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='faviroute',
            new_name='favorite',
        ),
    ]
